version: '3.1'
services:
  poems_rpc:
    image: poem:latest
    restart: always
    environment:
      RPC_HOST: poems_rpc
      RPC_PORT: 7789
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      CMS_USER: admin
      CMS_PASSWORD: password123
    command: poems-server
  admin_rpc:
    image: poem:latest
    restart: always
    environment:
      RPC_HOST: admin_rpc
      RPC_PORT: 7790
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      CMS_USER: admin
      CMS_PASSWORD: password123
    command: admin-server
  admin_frontend:
    image: poem:latest
    ports:
      - "7791:7791"
    restart: always
    environment:
      SERVER_HOST: admin_frontend
      SERVER_PORT: 7791
      RPC_HOST: admin_rpc
      RPC_PORT: 7790
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      CMS_USER: admin
      CMS_PASSWORD: password123
    command: admin-frontend
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: myrootpassword
    volumes:
      - db:/var/lib/mysql

volumes:
  db: