version: '3.1'
services:
  poems_rpc:
    image: poem:latest
    restart: always
    environment:
      RPC_HOST: poems_rpc
      RPC_PORT: 7789
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    command: poems-server
  admin_rpc:
    image: poem:latest
    restart: always
    environment:
      RPC_HOST: admin_rpc
      RPC_PORT: 7790
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    command: admin-server
  oauth_rpc:
    image: poem:latest
    restart: always
    environment:
      RPC_HOST: oauth_rpc
      RPC_PORT: 7792
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    command: oauth-server
  admin_frontend:
    image: poem:latest
    ports:
      - "7791:7791"
    restart: always
    environment:
      SERVER_HOST: admin_frontend
      SERVER_PORT: 7791
      ADMIN_RPC_HOST: admin_rpc
      ADMIN_RPC_PORT: 7790
      OAUTH_RPC_HOST: oauth_rpc
      OAUTH_RPC_PORT: 7792
      POEMS_RPC_HOST: poems_rpc
      POEMS_RPC_PORT: 7789
      HASH_KEY: "r6AU4ArEbR5DF55sHQQRZQVBTqNPf5JF"
      CRYPTO_KEY: "Kbb22QSGXta8BhMXQUqxsddqfZuB48dm"
    volumes:
     - sessions:/go/sessions 
    command: admin-frontend
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: myrootpassword
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  sessions: