// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: poems/poems.proto

package poems

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the category.
type PoemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *PoemsRequest) Reset() {
	*x = PoemsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poems_poems_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoemsRequest) ProtoMessage() {}

func (x *PoemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poems_poems_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoemsRequest.ProtoReflect.Descriptor instead.
func (*PoemsRequest) Descriptor() ([]byte, []int) {
	return file_poems_poems_proto_rawDescGZIP(), []int{0}
}

func (x *PoemsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// The response message containing poems content.
type PoemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool            `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Poems   map[int32]*Poem `protobuf:"bytes,2,rep,name=poems,proto3" json:"poems,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PoemsResponse) Reset() {
	*x = PoemsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poems_poems_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoemsResponse) ProtoMessage() {}

func (x *PoemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poems_poems_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoemsResponse.ProtoReflect.Descriptor instead.
func (*PoemsResponse) Descriptor() ([]byte, []int) {
	return file_poems_poems_proto_rawDescGZIP(), []int{1}
}

func (x *PoemsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PoemsResponse) GetPoems() map[int32]*Poem {
	if x != nil {
		return x.Poems
	}
	return nil
}

type Poem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Text  string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Poem) Reset() {
	*x = Poem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poems_poems_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Poem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poem) ProtoMessage() {}

func (x *Poem) ProtoReflect() protoreflect.Message {
	mi := &file_poems_poems_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poem.ProtoReflect.Descriptor instead.
func (*Poem) Descriptor() ([]byte, []int) {
	return file_poems_poems_proto_rawDescGZIP(), []int{2}
}

func (x *Poem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Poem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_poems_poems_proto protoreflect.FileDescriptor

var file_poems_poems_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x6f, 0x65, 0x6d, 0x73, 0x2f, 0x70, 0x6f, 0x65, 0x6d, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x0c, 0x50, 0x6f, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22,
	0x9b, 0x01, 0x0a, 0x0d, 0x50, 0x6f, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x2f, 0x0a, 0x05, 0x70,
	0x6f, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x50, 0x6f, 0x65,
	0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x6f, 0x65, 0x6d, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x70, 0x6f, 0x65, 0x6d, 0x73, 0x1a, 0x3f, 0x0a, 0x0a,
	0x50, 0x6f, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x50, 0x6f,
	0x65, 0x6d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x30, 0x0a,
	0x04, 0x50, 0x6f, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x32,
	0x34, 0x0a, 0x05, 0x50, 0x6f, 0x65, 0x6d, 0x73, 0x12, 0x2b, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x50,
	0x6f, 0x65, 0x6d, 0x73, 0x12, 0x0d, 0x2e, 0x50, 0x6f, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x50, 0x6f, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1a, 0x5a, 0x18, 0x77, 0x65, 0x62, 0x69, 0x6d, 0x69, 0x7a,
	0x65, 0x72, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x70, 0x6f, 0x65, 0x6d, 0x2f, 0x70, 0x6f, 0x65, 0x6d,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_poems_poems_proto_rawDescOnce sync.Once
	file_poems_poems_proto_rawDescData = file_poems_poems_proto_rawDesc
)

func file_poems_poems_proto_rawDescGZIP() []byte {
	file_poems_poems_proto_rawDescOnce.Do(func() {
		file_poems_poems_proto_rawDescData = protoimpl.X.CompressGZIP(file_poems_poems_proto_rawDescData)
	})
	return file_poems_poems_proto_rawDescData
}

var file_poems_poems_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_poems_poems_proto_goTypes = []interface{}{
	(*PoemsRequest)(nil),  // 0: PoemsRequest
	(*PoemsResponse)(nil), // 1: PoemsResponse
	(*Poem)(nil),          // 2: Poem
	nil,                   // 3: PoemsResponse.PoemsEntry
}
var file_poems_poems_proto_depIdxs = []int32{
	3, // 0: PoemsResponse.poems:type_name -> PoemsResponse.PoemsEntry
	2, // 1: PoemsResponse.PoemsEntry.value:type_name -> Poem
	0, // 2: Poems.GetPoems:input_type -> PoemsRequest
	1, // 3: Poems.GetPoems:output_type -> PoemsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_poems_poems_proto_init() }
func file_poems_poems_proto_init() {
	if File_poems_poems_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_poems_poems_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoemsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poems_poems_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoemsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poems_poems_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Poem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_poems_poems_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poems_poems_proto_goTypes,
		DependencyIndexes: file_poems_poems_proto_depIdxs,
		MessageInfos:      file_poems_poems_proto_msgTypes,
	}.Build()
	File_poems_poems_proto = out.File
	file_poems_poems_proto_rawDesc = nil
	file_poems_poems_proto_goTypes = nil
	file_poems_poems_proto_depIdxs = nil
}
