// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: poems/poems.proto

package poems

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CategoriesRequest_Status int32

const (
	CategoriesRequest_PUBLISHED CategoriesRequest_Status = 0
	CategoriesRequest_DRAFT     CategoriesRequest_Status = 1
)

// Enum value maps for CategoriesRequest_Status.
var (
	CategoriesRequest_Status_name = map[int32]string{
		0: "PUBLISHED",
		1: "DRAFT",
	}
	CategoriesRequest_Status_value = map[string]int32{
		"PUBLISHED": 0,
		"DRAFT":     1,
	}
)

func (x CategoriesRequest_Status) Enum() *CategoriesRequest_Status {
	p := new(CategoriesRequest_Status)
	*p = x
	return p
}

func (x CategoriesRequest_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CategoriesRequest_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_poems_poems_proto_enumTypes[0].Descriptor()
}

func (CategoriesRequest_Status) Type() protoreflect.EnumType {
	return &file_poems_poems_proto_enumTypes[0]
}

func (x CategoriesRequest_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CategoriesRequest_Status.Descriptor instead.
func (CategoriesRequest_Status) EnumDescriptor() ([]byte, []int) {
	return file_poems_poems_proto_rawDescGZIP(), []int{0, 0}
}

type CategoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status CategoriesRequest_Status `protobuf:"varint,1,opt,name=status,proto3,enum=CategoriesRequest_Status" json:"status,omitempty"`
}

func (x *CategoriesRequest) Reset() {
	*x = CategoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poems_poems_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoriesRequest) ProtoMessage() {}

func (x *CategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poems_poems_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoriesRequest.ProtoReflect.Descriptor instead.
func (*CategoriesRequest) Descriptor() ([]byte, []int) {
	return file_poems_poems_proto_rawDescGZIP(), []int{0}
}

func (x *CategoriesRequest) GetStatus() CategoriesRequest_Status {
	if x != nil {
		return x.Status
	}
	return CategoriesRequest_PUBLISHED
}

// The response message containing poems content.
type CategoriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success    bool                `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Categories map[int32]*Category `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CategoriesResponse) Reset() {
	*x = CategoriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poems_poems_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoriesResponse) ProtoMessage() {}

func (x *CategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poems_poems_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoriesResponse.ProtoReflect.Descriptor instead.
func (*CategoriesResponse) Descriptor() ([]byte, []int) {
	return file_poems_poems_proto_rawDescGZIP(), []int{1}
}

func (x *CategoriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CategoriesResponse) GetCategories() map[int32]*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

// The request message containing the category.
type PoemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *PoemsRequest) Reset() {
	*x = PoemsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poems_poems_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoemsRequest) ProtoMessage() {}

func (x *PoemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poems_poems_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoemsRequest.ProtoReflect.Descriptor instead.
func (*PoemsRequest) Descriptor() ([]byte, []int) {
	return file_poems_poems_proto_rawDescGZIP(), []int{2}
}

func (x *PoemsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// The response message containing poems content.
type PoemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool            `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Poems   map[int32]*Poem `protobuf:"bytes,2,rep,name=poems,proto3" json:"poems,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PoemsResponse) Reset() {
	*x = PoemsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poems_poems_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoemsResponse) ProtoMessage() {}

func (x *PoemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poems_poems_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoemsResponse.ProtoReflect.Descriptor instead.
func (*PoemsResponse) Descriptor() ([]byte, []int) {
	return file_poems_poems_proto_rawDescGZIP(), []int{3}
}

func (x *PoemsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PoemsResponse) GetPoems() map[int32]*Poem {
	if x != nil {
		return x.Poems
	}
	return nil
}

type Poem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Text  string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Poem) Reset() {
	*x = Poem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poems_poems_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Poem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poem) ProtoMessage() {}

func (x *Poem) ProtoReflect() protoreflect.Message {
	mi := &file_poems_poems_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poem.ProtoReflect.Descriptor instead.
func (*Poem) Descriptor() ([]byte, []int) {
	return file_poems_poems_proto_rawDescGZIP(), []int{4}
}

func (x *Poem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Poem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Category struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
}

func (x *Category) Reset() {
	*x = Category{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poems_poems_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_poems_poems_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_poems_poems_proto_rawDescGZIP(), []int{5}
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

var File_poems_poems_proto protoreflect.FileDescriptor

var file_poems_poems_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x6f, 0x65, 0x6d, 0x73, 0x2f, 0x70, 0x6f, 0x65, 0x6d, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x6a, 0x0a, 0x11, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x22, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x53, 0x48,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x52, 0x41, 0x46, 0x54, 0x10, 0x01, 0x22,
	0xbd, 0x01, 0x0a, 0x12, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x43, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x48, 0x0a, 0x0f, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x2a, 0x0a, 0x0c, 0x50, 0x6f, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x9b, 0x01, 0x0a, 0x0d,
	0x50, 0x6f, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x2f, 0x0a, 0x05, 0x70, 0x6f, 0x65, 0x6d, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x50, 0x6f, 0x65, 0x6d, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x6f, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x05, 0x70, 0x6f, 0x65, 0x6d, 0x73, 0x1a, 0x3f, 0x0a, 0x0a, 0x50, 0x6f, 0x65, 0x6d,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x50, 0x6f, 0x65, 0x6d, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x30, 0x0a, 0x04, 0x50, 0x6f, 0x65,
	0x6d, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x32, 0x0a, 0x08, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x6c, 0x75, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x32,
	0x70, 0x0a, 0x05, 0x50, 0x6f, 0x65, 0x6d, 0x73, 0x12, 0x2b, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x50,
	0x6f, 0x65, 0x6d, 0x73, 0x12, 0x0d, 0x2e, 0x50, 0x6f, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x50, 0x6f, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x12, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x1a, 0x5a, 0x18, 0x77, 0x65, 0x62, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x64,
	0x65, 0x76, 0x2f, 0x70, 0x6f, 0x65, 0x6d, 0x2f, 0x70, 0x6f, 0x65, 0x6d, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_poems_poems_proto_rawDescOnce sync.Once
	file_poems_poems_proto_rawDescData = file_poems_poems_proto_rawDesc
)

func file_poems_poems_proto_rawDescGZIP() []byte {
	file_poems_poems_proto_rawDescOnce.Do(func() {
		file_poems_poems_proto_rawDescData = protoimpl.X.CompressGZIP(file_poems_poems_proto_rawDescData)
	})
	return file_poems_poems_proto_rawDescData
}

var file_poems_poems_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_poems_poems_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_poems_poems_proto_goTypes = []interface{}{
	(CategoriesRequest_Status)(0), // 0: CategoriesRequest.Status
	(*CategoriesRequest)(nil),     // 1: CategoriesRequest
	(*CategoriesResponse)(nil),    // 2: CategoriesResponse
	(*PoemsRequest)(nil),          // 3: PoemsRequest
	(*PoemsResponse)(nil),         // 4: PoemsResponse
	(*Poem)(nil),                  // 5: Poem
	(*Category)(nil),              // 6: Category
	nil,                           // 7: CategoriesResponse.CategoriesEntry
	nil,                           // 8: PoemsResponse.PoemsEntry
}
var file_poems_poems_proto_depIdxs = []int32{
	0, // 0: CategoriesRequest.status:type_name -> CategoriesRequest.Status
	7, // 1: CategoriesResponse.categories:type_name -> CategoriesResponse.CategoriesEntry
	8, // 2: PoemsResponse.poems:type_name -> PoemsResponse.PoemsEntry
	6, // 3: CategoriesResponse.CategoriesEntry.value:type_name -> Category
	5, // 4: PoemsResponse.PoemsEntry.value:type_name -> Poem
	3, // 5: Poems.GetPoems:input_type -> PoemsRequest
	1, // 6: Poems.GetCategories:input_type -> CategoriesRequest
	4, // 7: Poems.GetPoems:output_type -> PoemsResponse
	2, // 8: Poems.GetCategories:output_type -> CategoriesResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_poems_poems_proto_init() }
func file_poems_poems_proto_init() {
	if File_poems_poems_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_poems_poems_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poems_poems_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poems_poems_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoemsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poems_poems_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoemsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poems_poems_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Poem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poems_poems_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_poems_poems_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poems_poems_proto_goTypes,
		DependencyIndexes: file_poems_poems_proto_depIdxs,
		EnumInfos:         file_poems_poems_proto_enumTypes,
		MessageInfos:      file_poems_poems_proto_msgTypes,
	}.Build()
	File_poems_poems_proto = out.File
	file_poems_poems_proto_rawDesc = nil
	file_poems_poems_proto_goTypes = nil
	file_poems_poems_proto_depIdxs = nil
}
