// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: oauth/oauth.proto

package oauth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PoemsClient is the client API for Poems service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PoemsClient interface {
	// Authenticate user with given credentials
	AuthUser(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type poemsClient struct {
	cc grpc.ClientConnInterface
}

func NewPoemsClient(cc grpc.ClientConnInterface) PoemsClient {
	return &poemsClient{cc}
}

func (c *poemsClient) AuthUser(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/Poems/AuthUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoemsServer is the server API for Poems service.
// All implementations must embed UnimplementedPoemsServer
// for forward compatibility
type PoemsServer interface {
	// Authenticate user with given credentials
	AuthUser(context.Context, *AuthRequest) (*AuthResponse, error)
	mustEmbedUnimplementedPoemsServer()
}

// UnimplementedPoemsServer must be embedded to have forward compatible implementations.
type UnimplementedPoemsServer struct {
}

func (UnimplementedPoemsServer) AuthUser(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthUser not implemented")
}
func (UnimplementedPoemsServer) mustEmbedUnimplementedPoemsServer() {}

// UnsafePoemsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PoemsServer will
// result in compilation errors.
type UnsafePoemsServer interface {
	mustEmbedUnimplementedPoemsServer()
}

func RegisterPoemsServer(s grpc.ServiceRegistrar, srv PoemsServer) {
	s.RegisterService(&Poems_ServiceDesc, srv)
}

func _Poems_AuthUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoemsServer).AuthUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Poems/AuthUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoemsServer).AuthUser(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Poems_ServiceDesc is the grpc.ServiceDesc for Poems service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Poems_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Poems",
	HandlerType: (*PoemsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthUser",
			Handler:    _Poems_AuthUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oauth/oauth.proto",
}
